version: '3.3'
services:

  wildfly-site-in:
    build:
      context: .
      dockerfile: Dockerfile-site
      args:
        WILDFLY_NAME: wildfly-site-in
        CLUSTER_PW: rootadmin
    image: wildfly-site-in:latest
    container_name: wildfly-site-in
    ports:
      - 18080:8080
      - 19990:9990
    restart: always
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    networks:
      sbdsp:

  wildfly-site-ex:
    build:
      context: .
      dockerfile: Dockerfile-site
      args:
        WILDFLY_NAME: wildfly-site-ex
        CLUSTER_PW: rootadmin
    image: wildfly-site-ex:latest
    container_name: wildfly-site-ex
    ports:
      - 18081:8080
      - 19991:9990
    restart: always
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    networks:
      sbdsp:

  wildfly-down:
    build:
      context: .
      dockerfile: Dockerfile-down
      args:
        WILDFLY_NAME: wildfly-down
        CLUSTER_PW: rootadmin
    image: wildfly-down:latest
    container_name: wildfly-down
    ports:
      - 18082:8080
      - 19992:9990
    restart: always
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    networks:
      sbdsp:

networks:
  sbdsp:
    ipam:
      driver: default

